name: '[PRN] Quality Engineering'

on:
  pull_request:
    branches:
      - main
      - master
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  quality-engineering:
    name: QE
    uses: vtex-apps/usqa/.github/workflows/quality-engineering.yml@main
    with:
      danger: true
      dangerRequireChangelog: false
      nodeLint: true
      nodeTest: true
      nodeSonar: true
      nodeSonarProjectKey: vtex-apps_availability-notify-ts
      nodeSonarOrganization: vtex-apps
      dotnetSonar: true
      dotnetSonarProjectKey: vtex-apps_availability-notify-dotnet
      dotnetSonarOrganization: vtex-apps
      cypress: false
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      sonarToken: ${{ secrets.SONAR_TOKEN }}
      cypressJson: ${{ secrets.VTEX_QE }}
